spring:
  profiles:
    active: dev

---

server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        #mybatis配置文件所在路径
  type-aliases-package: com.zlc.base.entity                # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml     # mapper映射文件

spring:
  profiles: dev # 开发环境
  application:
    name: product-provider-dev #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT  # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                      # 等待连接获取的最大超时时间

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:81/eureka/,http://127.0.0.1:82/eureka/,http://127.0.0.1:83/eureka/

#dashboard监控配置
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

---

server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        #mybatis配置文件所在路径
  type-aliases-package: com.zlc.base.entity                # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml     # mapper映射文件

spring:
  profiles: prod # 开发环境
  application:
    name: product-provider-prod #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT  # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                      # 等待连接获取的最大超时时间

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:81/eureka/,http://127.0.0.1:82/eureka/,http://127.0.0.1:83/eureka/

#dashboard监控配置
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream